import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, ArrowUpRight } from 'lucide-react'
import Scene from '../components/Scene'
import CTA from '../components/CTA'
import { services, process } from '../data/content'

export default function Home(){return <>
<section className="relative min-h-[780px] overflow-hidden bg-[#F7F9FC] bg-radial-soft"><div className="absolute inset-0 grid-fade opacity-50"/><div className="container-shell relative grid min-h-[700px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="eyebrow">Independent Business & Financial Advisory</div><h1 className="mt-6 max-w-5xl font-display text-[48px] leading-[.98] tracking-[-.04em] text-navy-900 sm:text-6xl lg:text-[78px]">Better decisions. Stronger businesses. Sustainable value.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-navy-900/65">ROHAMA Ventures combines financial expertise, commercial insight, analytical capability and practical business experience to help clients navigate complex decisions.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex items-center gap-2 rounded-full bg-navy-900 px-6 py-3.5 text-sm font-semibold text-white">Discuss your challenge <ArrowUpRight size={16}/></Link><Link to="/services" className="inline-flex items-center gap-2 rounded-full border border-navy-900/15 bg-white px-6 py-3.5 text-sm font-semibold text-navy-900">Explore services <ArrowRight size={16}/></Link></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-navy-900/10 pt-6 text-xs uppercase tracking-[.18em] text-navy-900/45"><span>Insight</span><span>Analysis</span><span>Strategy</span><span>Value</span></div></motion.div><div className="relative h-[420px] lg:h-[580px]"><div className="absolute inset-[10%] rounded-full bg-gold-400/10 blur-3xl"/><Scene/><div className="pointer-events-none absolute bottom-5 left-1/2 -translate-x-1/2 rounded-full border border-white/70 bg-white/70 px-4 py-2 text-[10px] uppercase tracking-[.2em] text-navy-900/50 backdrop-blur">Interactive advisory model</div></div></div></section>
<section className="bg-white py-20 lg:py-28"><div className="container-shell"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><div className="eyebrow">Who we are</div><h2 className="mt-5 font-display text-4xl leading-tight text-navy-900 sm:text-5xl">A trusted partner for business & financial advisory.</h2></div><div className="grid gap-6 sm:grid-cols-3"><Stat n="01" t="Structured Methodology" b="A defined seven-stage process for every assignment."/><Stat n="02" t="Experienced Resource Network" b="Professionals with strong finance and advisory credentials."/><Stat n="03" t="Broad Deliverable Range" b="From due diligence reports to financial models and board packs."/></div></div></div></section>
<section className="bg-mist py-20 lg:py-28"><div className="container-shell"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">What we do</div><h2 className="mt-4 font-display text-4xl text-navy-900 sm:text-5xl">Five pillars. One advisory relationship.</h2></div><Link to="/services" className="text-sm font-semibold text-navy-900">View all services →</Link></div><div className="mt-10 grid gap-4 lg:grid-cols-5">{services.map((s,i)=><motion.div whileHover={{y:-7}} transition={{type:'spring',stiffness:220}} key={s.slug}><Link to={`/services/${s.slug}`} className="group flex min-h-[340px] flex-col rounded-[1.6rem] bg-navy-900 p-6 text-white shadow-soft"><div className="font-display text-4xl text-gold-400">{s.number}</div><div className="mt-auto"><div className="text-lg font-semibold leading-snug">{s.title}</div><p className="mt-3 text-sm leading-6 text-white/50">{s.short}</p><div className="mt-5 inline-flex items-center gap-2 text-xs text-gold-400">Explore <ArrowUpRight size={14}/></div></div></Link></motion.div>)}</div></div></section>
<section className="bg-white py-20 lg:py-28"><div className="container-shell"><div className="grid items-start gap-12 lg:grid-cols-[.85fr_1.15fr]"><div className="lg:sticky lg:top-28"><div className="eyebrow">Our philosophy</div><h2 className="mt-5 font-display text-4xl leading-tight sm:text-5xl">Good decisions need more than good numbers.</h2><p className="mt-6 max-w-lg text-base leading-8 text-navy-900/60">We combine financial analysis, commercial evaluation, strategic thinking and practical implementation in every assignment.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Where does the business currently stand?','Why are financial and operational results changing?','What risks may affect the business?','What opportunities are available?','What is the business worth?','How should capital be deployed?','Does an acquisition or investment make commercial sense?','How should debt and financing be structured?'].map((q,i)=><div key={q} className="rounded-2xl border border-navy-900/10 bg-mist p-5"><span className="text-xs text-gold-500">0{i+1}</span><p className="mt-3 text-sm font-medium leading-6 text-navy-900">{q}</p></div>)}</div></div></div></section>
<section className="overflow-hidden bg-navy-950 py-20 text-white lg:py-28"><div className="container-shell"><div className="eyebrow">Our approach</div><div className="mt-4 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><h2 className="font-display text-4xl leading-tight sm:text-5xl">A structured, seven-stage engagement methodology.</h2><p className="max-w-xl text-base leading-8 text-white/55">Every engagement follows a transparent path while keeping recommendations grounded in a clear understanding of the business.</p></div><div className="mt-14 overflow-x-auto pb-2"><div className="grid min-w-[980px] grid-cols-7">{process.map((p,i)=><div className="relative border-t border-white/15 pt-7 pr-5" key={p[1]}><span className="absolute -top-[5px] left-0 h-2.5 w-2.5 rounded-full bg-gold-400"/><div className="font-display text-3xl text-gold-400">{p[0]}</div><div className="mt-3 font-semibold">{p[1]}</div><p className="mt-2 text-xs leading-5 text-white/45">{p[2]}</p></div>)}</div></div></div></section>
<CTA/></>}
function Stat({n,t,b}){return <div className="rounded-3xl border border-navy-900/10 bg-mist p-6"><div className="font-display text-3xl text-gold-500">{n}</div><h3 className="mt-8 font-semibold text-navy-900">{t}</h3><p className="mt-3 text-sm leading-6 text-navy-900/55">{b}</p></div>}
